var team_mapping = {
  "MTL": "Montréal",
  "TOR": "Toronto",
  "PIT": "Pittsburgh",
  "NYR": "NY Rangers",
  "COL": "Colorado",
  "DET": "Detroit",
  "NYI": "NY Islanders",
  "BOS": "Boston",
  "BUF": "Buffalo",
  "CBJ": "Columbus",
  "CHI": "Chicago",
  "ARI": "Arizona",
  "OTT": "Ottawa",
  "NSH": "Nashville",
  "TBL": "Tampa Bay",
  "WSH": "Washington",
  "DAL": "Dallas",
  "NJD": "New Jersey",
  "VAN": "Vancouver",
  "CGY": "Calgary",
  "LAK": "Los Angeles",
  "ANA": "Anaheim",
  "CAR": "Carolina",
  "PHI": "Philadelphia",
  "FLA": "Florida",
  "MIN": "Minnesota",
  "WPG": "Winnipeg",
  "SJS": "San Jose",
  "STL": "St. Louis",
  "EDM": "Edmonton"
}

module.exports = team_mapping
